### ISSUE TITLE
Unlink the fork

### ISSUE THREAD

**Issue by sdruskat** [CfA-Library/citesoftware.org2#8]

**Comment by jspaaks** [comment]
While unlinking, we should consider uploading a snapshot of the files that are there now, so in effect flattening git history.

**Comment by sdruskat** [comment]
Repo is moved, need to double-check that everything works before closing. GH Pages still has hiccups.

**Comment by sdruskat** [comment]
So, with this theme and the Jekyll action we use, the `baseurl` in `_config.yml` must be the *name of the repository* (currently `citesoftware.org2`) for the deploy to resolve assets properly 🤷.

Squashed changes and fixed in 5ca89ede620d7a2fc69ab62697673a64cf198f9a, and documenting this for fixing after we rename the repository in #10.
